### ISSUE TITLE
libstdc++.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by amiltonwong** [udacity/FCND-Simulator-Releases#1]
Hi, all,

I had downloaded linux version of Preview - v0.0.2 simulator. However, I came across the following error after running `./FCND-Sim_Linux`

```
root@milton-ThinkCentre-M93p:/data/code/FCND-Term1-all/simulator# ./FCND-Sim_Linux
./FCND-Sim_Linux: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

My system is ubuntu 16.04 64 bit, could anyone give some suggestion to fix this issue? THX!

**Comment by amiltonwong** [comment]
after `apt-get install lib32stdc++6`, the problem is solved. THX!

**Comment by domluna** [comment]
@amiltonwong It seems the Linux builds were only 32-bit, I've uploaded a universal build which includes 32-bit and 64-bit versions here - https://github.com/udacity/FCND-Simulator-Releases/releases/tag/v0.0.3-preview, it's called `linux-universal.zip`. In the future the Linux builds will be 32-bit and 64-bit to avoid this issue.
